#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
# yabai -m config mouse_follows_focus          on
# yabai -m config focus_follows_mouse          off
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1
yabai -m config normal_window_opacity        1
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config window_border_radius         0
yabai -m config active_window_border_color   0xFF88C0D0
yabai -m config normal_window_border_color   on
yabai -m config insert_feedback_color        0xff61afef
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp
yabai -m config top_padding                  25
yabai -m config bottom_padding               2
yabai -m config left_padding                 2 
yabai -m config right_padding                2
yabai -m config window_gap                   1

# yabai -m space 1 --label 1
# yabai -m space 2 --label 2
# yabai -m space 3 --label 3
# yabai -m space 4 --label 4
# yabai -m space 5 --label 5
# yabai -m space 6 --label 6
# yabai -m space 7 --label 7
# yabai -m space 8 --label 8
# yabai -m space 9 --label 9
# yabai -m space 10 --label 10
#
# yabai -m rule --add app="Code" space=1
# yabai -m rule --add app="Firefox" space=2
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="PS Remote Play" manage=off
yabai -m rule --add app="Steam" manage=off

### Sketchybar ###
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"         # Notify sketchybar when space changes
yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change"   # Notify sketchybar when the focused app changes
